import turtle

screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("tan")
t=turtle.Turtle()
t.speed(0)

t.setheading(0)
t.penup()
t.goto(-80,15)
t.pencolor("blue")
t.pensize(2)
t.pendown()
t.circle(35)
t.penup()
t.goto(0,15)
t.pencolor("black")
t.pensize(2)
t.pendown()
t.circle(35)
t.penup()
t.goto(80,15)
t.pencolor("red")
t.pensize(2)
t.pendown()
t.circle(35)
t.penup()
t.goto(-40,-15)
t.pencolor("yellow")
t.pensize(2)
t.pendown()
t.circle(35)
t.penup()
t.goto(40,-15)
t.pencolor("green")
t.pensize(2)
t.pendown()
t.circle(35)

t.penup()
t.goto(0,100)#1
t.pencolor('purple')
t.pendown()
t.write("Winter Olympics",font=("Arial",30,"bold italic"),align="center")
t.penup()
t.goto(0,-100)#1
t.pendown()
t.write("2026",font=("Arial",30,"bold italic"),align="center")

turtle.done()
